---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wetap/public_html/2025/skynet

    - /bin/mkdir -p $DEPLOYPATH

    - /bin/cp -R application $DEPLOYPATH

    - /bin/cp -R system $DEPLOYPATH

    - /bin/cp -R assets $DEPLOYPATH

    - /bin/cp index.php $DEPLOYPATH
