---
deployment:
  tasks:
    - export DEPLOYPATH=/home/CPANELUSER/public_html/
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
